"""
Logging filters for RSS Bridge.
"""

import logging


class BaseFilter(logging.Filter):
    """
    Base filter for all custom logging filters.
    """

    def filter(self, record: logging.LogRecord) -> bool:
        return True


class IgnoreHealthCheckFilter(BaseFilter):
    """
    Ignore logs generated by the health endpoint.
    """

    def filter(self, record: logging.LogRecord) -> bool:

        message = record.getMessage().lower()

        return "/health" not in message


class IgnoreStaticFilesFilter(BaseFilter):
    """
    Ignore logs for static resources.
    """

    STATIC_EXTENSIONS = (
        ".css",
        ".js",
        ".png",
        ".jpg",
        ".jpeg",
        ".gif",
        ".svg",
        ".ico",
        ".woff",
        ".woff2",
        ".ttf",
        ".map"
    )

    def filter(self, record: logging.LogRecord) -> bool:

        message = record.getMessage().lower()

        return not any(
            extension in message
            for extension in self.STATIC_EXTENSIONS
        )


class IgnoreOptionsFilter(BaseFilter):
    """
    Ignore HTTP OPTIONS requests.
    """

    def filter(self, record: logging.LogRecord) -> bool:

        message = record.getMessage().upper()

        return "OPTIONS" not in message


class MinimumLevelFilter(BaseFilter):
    """
    Allow only logs at or above a minimum level.
    """

    def __init__(self, level: int):

        super().__init__()

        self.level = level

    def filter(self, record: logging.LogRecord) -> bool:

        return record.levelno >= self.level